framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    annotations:
        enabled: true
        cache: annotations.cache 

    serializer:
        enabled: true
        name_converter: null
        circular_reference_handler: null

    validation:
        enabled: true
        enable_annotations: true

    mailer:
        dsn: '%env(MAILER_DSN)%'
        
    translator:
        default_locale: ru
        fallbacks:
            - ru
            - en
            
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        
    form:
        enabled: true
        
    php_errors:
        log: true
        
    assets:
        enabled: true
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        
    profiler:
        enabled: '%kernel.debug%'
        collect: true
        
    cache:
        app: cache.adapter.redis
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'
        
    fragments:
        enabled: true
        path: /_fragment
        
    http_client:
        enabled: true
        default_options:
            max_redirects: 7
            timeout: 30
            
    web_link:
        enabled: true
        
    default_locale: ru
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    ide: 'phpstorm://open?file=%%f&line=%%l'
    
    error_controller: 'error_controller::show'