framework:
    serializer:
        enabled: true
        cache: 'clinic.serializer_cache'
        enable_annotations: true
        name_converter: serializer.name_converter.camel_case_to_snake_case
        mapping:
            paths:
                - '%kernel.project_dir%/src/Entity'